version: "3"
services:
  serverapp:
    container_name: server
    image: server
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - serverbdd
  serverbdd:
    image: bdd
    build: ./bdd
    ports:
      - "5432:5432"

