version: "3"
services:
  server_app:
    container_name: server
    image: server
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_server
  postgres_server:
    image: bdd
    build: ./bdd
    ports:
      - "5432:5432"

